### ISSUE TITLE
[12.0] base_geoengine_demo fails to install

### ISSUE THREAD

**Issue by gitlcp** [OCA/geospatial#206]
![TIM图片20190713053438](https://user-images.githubusercontent.com/34472501/61167533-07ab4e00-a573-11e9-813f-8dfd5b217453.png)
helpe me ,thanks you

**Comment by pedrobaeza** [comment]
Are you trying on OCA runbot?

**Comment by gitlcp** [comment]
no @pedrobaeza

**Comment by gitlcp** [comment]
I'm just running the source code for odoo12 locally. @pedrobaeza

**Comment by brian10048** [comment]
@pedrobaeza This is also happening on the runbot.  I just rebuilt the 12.0 branch and the same error occurs

`Traceback (most recent call last):
  File "/home/odoo/odoo-12.0/odoo/service/server.py", line 1116, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/odoo-12.0/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/odoo-12.0/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/odoo/odoo-12.0/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/odoo-12.0/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/home/odoo/odoo-12.0/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/odoo/odoo-12.0/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/odoo/odoo-12.0/odoo/tools/convert.py", line 865, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/odoo/odoo-12.0/odoo/tools/convert.py", line 764, in parse
    exc_info[2]
  File "/home/odoo/odoo-12.0/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/odoo/odoo-12.0/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/odoo/odoo-12.0/odoo/tools/convert.py", line 650, in _tag_record
    f_val = self.id_get(f_ref)
  File "/home/odoo/odoo-12.0/odoo/tools/convert.py", line 741, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/home/odoo/odoo-12.0/odoo/tools/convert.py", line 747, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/home/odoo/odoo-12.0/odoo/addons/base/models/ir_model.py", line 1404, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-25>", line 2, in xmlid_lookup
  File "/home/odoo/odoo-12.0/odoo/tools/cache.py", line 93, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/odoo-12.0/odoo/addons/base/models/ir_model.py", line 1393, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
odoo.tools.convert.ParseError: "External ID not found in the system: base_geoengine_demo.field_dummy_zip__the_geom" while parsing /home/odoo/build/OCA/geospatial/base_geoengine_demo/views/zip.xml:76, near
<record id="geoengine_vector_layer_basictest0" model="geoengine.vector.layer">
  <field name="geo_field_id" ref="base_geoengine_demo.field_dummy_zip__the_geom"/>
  <field name="name">Basic ZIP</field>
  <field name="view_id" ref="ir_ui_view_resbetterzipgeoview0"/>
  <field name="geo_repr">basic</field>
  <field name="attribute_field_id" ref="field_dummy_zip__city"/>
  <field name="begin_color">#FF680A</field>
</record>
Message not found: 'Modules loaded.'`

See related discussion here: https://github.com/OCA/field-service/pull/258#issuecomment-508414478 from @murtuzasaleh

**Comment by yvaucher** [comment]
@gitlcp according to https://github.com/OCA/field-service/pull/258#issuecomment-508414478 the issue comes from an Odoo commit and the fix has been merged since.

Did it solve your issue?

**Comment by brian10048** [comment]
@yvaucher that commit was merged about 15 days ago.  Would the OCA runbot be using the updated Odoo code by now?  I haven't tried myself locally with up to date Odoo, but the OCA runbot I rebuilt about an hour ago is still having this error https://runbot.odoo-community.org/runbot/build/3379120

**Comment by yvaucher** [comment]
@brian10048 

OCA runbot uses oca/OCB which is synchronized with odoo/odoo at worst it could be 24 hours behind, it's unlikely that it 15 days behind. Just checked it and it seems still working fine. Thus, it's not fixed :disappointed: 

In the runbot you linked I see external ids for other modules, thus it could be the type of field with geo fields that doesn't trigger the xml id generation somehow.

commenting the lines with in xml files with the geo_field_id should make the module installable. But then we would have to set them by hand.

For now a temporary solution would be to revert the commit  https://github.com/odoo/odoo/commit/547118d76fbd7c34bc164f304b0b9ca3031f4a10 .

Which seems to be there only for manually added fields.

@murtuzasaleh do you have more info on this? How did you solved it for field-service ?

**Comment by gitlcp** [comment]
When the new odoo source is referenced, the installation is successful

**Comment by max3903** [comment]
@brian10048 We must be doing something wrong in `fieldservice_geoengine`. There is no XML ID of the new `fsm.location` and `fsm.order` fields (shape).

**Comment by max3903** [comment]
@brian10048 Here is my attempt to fix this bug: https://github.com/OCA/field-service/pull/299

**Comment by brian10048** [comment]
@gitlcp it seems this has been resolved for you.  If so, may this be closed?

Thanks @max3903. I will check it out over there soon

**Comment by brian10048** [comment]
@max3903 I did a clean install with up to date Odoo source.  This is still an issue for `base_geoengine_demo` and `fieldservice_geoengine`

As @yvaucher suggested, I commented the lines causing the issue and avoided loading the vector layer records altogether in order to install the module.

After installing, I did an export of the fields data and received the following.  It shows the XML ID for the geo fields is not being generated in the format we are expecting like they were before the changes in Odoo source.
  
`"External ID","Field Name","Field Label","Field Type","Indexed","Model","Object Relation","Readonly","Stored","Type"
"__export__.ir_model_fields_1700_939bcbfe","the_point","Coordinate","geo_point","False","base_geoengine_demo.model_geoengine_demo_automatic_retailing_machine","","False","True","Custom Field"
"base.field_ir_actions_server__help","help","Action Description","html","False","base.model_ir_actions_server","","False","True","Base Field"
`

I'm not sure where to go from here... Can we do something to make these `Base` fields instead of `Custom` in order to get the XML ID generated? Or does the change need to happen upstream in Odoo source?

**Comment by max3903** [comment]
@brian10048 It must be how GeoPoint fields are managed. They show up as custom field instead of base one. @yvaucher Any hints?

**Comment by max3903** [comment]
@yvaucher Same issue in the 12.0 branch:
https://travis-ci.org/OCA/geospatial/jobs/564786539#L1045

**Comment by yvaucher** [comment]
The fix #218 should solve this issue. Fields with state `manual` don't have xml ids. And geo fields were wrongly defined as `manual`.
